[package]
name = "engine"
version = "0.1.0"
edition.workspace = true

[dependencies]
corelib = { path = "../core" } 
chrono = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true }